### ISSUE TITLE
Node 12/NodeNext module resolution breaks vue file organize imports

### ISSUE THREAD

**Issue by kalvenschraut** [simonhaenisch/prettier-plugin-organize-imports#63]
Noticed this issue after I tried my fix in PR #62 . While that PR fixes the initial issue, ran into a new one that only occurs for vue files.

Note my editor organize imports command works just fine to sort the vue file

Repro found [here](https://github.com/RtVision/organize-imports-vue-node-next-repro)

Error Stack Trace

```
apps/app-ui/src/components/CoreAdminDashboard.vue[error] apps/app-ui/src/components/CoreAdminDashboard.vue: TypeError: node.insertChildBefore is not a function
[error]     at /home/kalvens/rtvision-app/mono/node_modules/.pnpm/prettier@2.7.1/node_modules/prettier/index.js:34818:22
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37526)
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37518)
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37518)
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37518)
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37518)
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37518)
[error]     at vs.walk (/home/kalvens/open-source/prettier-plugin-organize-imports/node_modules/.pnpm/prettier@2.4.1/node_modules/prettier/parser-html.js:61:37518)
[error]     at extractInterpolation (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/prettier@2.7.1/node_modules/prettier/index.js:34802:11)
[error]     at Object.preprocess (/home/kalvens/rtvision-app/mono/node_modules/.pnpm/prettier@2.7.1/node_modules/prettier/index.js:34709:9)
```

**Comment by simonhaenisch** [comment]
Can you please try out version `3.0.1` and let me know if that fixes anything?

**Comment by kalvenschraut** [comment]
Was able to use prettier on my whole codebase successfully with this plugin now so appears to be working now. Thanks for help in doing so!
